FROM uselagoon/php-7.4-cli-drupal:latest

COPY composer.json /app/composer.json

ENV COMPOSER_MEMORY_LIMIT=-1
RUN composer global remove hirak/prestissimo \
    && composer selfupdate --2 \
    && composer install -d /app \
    && composer clearcache

# Add composer bin to PATH
ENV PATH="/app/bin:${PATH}"

# Define where the Drupal Root is located
ENV WEBROOT=web