ARG CYPRESS_VERSION
FROM cypress/included:${CYPRESS_VERSION}

# point Cypress at the /root/cache no matter what user account is used
# see https://on.cypress.io/caching
ENV CYPRESS_CACHE_FOLDER=/root/.cache/Cypress